M48
; DRILL file {KiCad 8.0.0} date 2024-03-27T19:15:30-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-03-27T19:15:30-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0669
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1925
%
G90
G05
T1
X3.4024Y-4.2717
X3.678Y-4.2717
T2
X3.4909Y-4.7185
X3.4909Y-5.6752
M30
